# Generated by Django 4.1.5 on 2023-01-06 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default=None, max_length=100, null=True, unique=True)),
                ('role', models.CharField(choices=[('TE', 'Teacher'), ('HM', 'Head Master'), ('ST', 'Student')], default='ST', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, default=None, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexnetic_school.member')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intake_year', models.IntegerField(default=0)),
                ('f_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexnetic_school.class')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexnetic_school.member')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='personal_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lexnetic_school.personalinfo'),
        ),
        migrations.AddField(
            model_name='member',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexnetic_school.school'),
        ),
        migrations.CreateModel(
            name='HeadMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexnetic_school.member')),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lexnetic_school.school')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexnetic_school.school'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexnetic_school.teacher'),
        ),
    ]
